### PR TITLE
Copying the old frontend code

### PR DESCRIPTION
**Pull request by amireldor**
FIY: I wanted to write **dumb** and not "dump" in the commit message.

This is a beginning of a [Riot.js](http://riotjs.com/) "mobile-first" web app. It uses [Rollup](https://github.com/rollup/rollup) as the package bundler which is lovely.

TypeScript is not used - I might want to switch to using it or try using Flow for type checking.

### CODE REVIEW

**Comment by amireldor** [comment]
whoa, what did I do? I did `git flow feature finish`, but I see GitHub don't realize I merged this!

**Comment by tomgoren** [comment]
Right - that's why I have [this wrapper](https://gist.github.com/tomgoren/f53d35bb46be7e726c8a3db5a6c56678).

**Comment by tomgoren** [comment]
For the record - the actual bug:

https://github.com/petervanderdoes/gitflow-avh/issues/201

And someone from Globality issued a [PR](https://github.com/petervanderdoes/gitflow-avh/pull/330) that fixes it, but who knows when/if it will be merged.

**Comment by amireldor** [comment]
I read the script. How come you finish the branch without deleting, push, then delete the branch remotely, all without waiting for  a manual PR?

**Comment by tomgoren** [comment]
We only run this after the PR has been approved.

**Comment by amireldor** [comment]
What extra does it do in addition to "feature finish"? I don't have time to think at the moment. Thanks.

**Comment by tomgoren** [comment]
Basically it boils down to the instructions [here](https://github.com/petervanderdoes/gitflow-avh/issues/201#issuecomment-241231574). Keep the local branch, push it, and only then delete.

The problem with the existing functionality is that it merges and pushes, but does so in an order that makes GitHub PRs show up as "closed" instead of as "merged".

**Pull request closed without merging**
